<div style="padding: 5px;font-family:微软雅黑;">
<table class="tableForm" width="100%">
	<tr>
		<th>id:</th>
		<td>${metaService.id}</td>
	</tr>					
	<tr>
		<th width="25%">服务名称:</th>
		<td>${metaService.serviceName}</td>
	</tr>					
	<tr>
		<th>版本号:</th>
		<td>${metaService.version}</td>
	</tr>					
	<tr>
		<th>服务描述:</th>
		<td>${metaService.serviceDesc}</td>
	</tr>					
	<tr>
		<th>服务响应类型:</th>
		<td>${metaService.responseType}</td>
	</tr>					
	<tr>
		<th>所属系统:</th>
		<td>${metaService.owner}</td>
	</tr>					
	<tr>
		<th>服务名称:</th>
		<td>${metaService.busiType}</td>
	</tr>					
	<tr>
		<th>服务介绍:</th>
		<td>${metaService.note}</td>
	</tr>					
	<tr>
		<th>服务类:</th>
		<td>${metaService.serviceClass}</td>
	</tr>					
	<tr>
		<th>请求类:</th>
		<td>${metaService.requestClass}</td>
	</tr>					
	<tr>
		<th>同步响应类:</th>
		<td>${metaService.responseClass}</td>
	</tr>					
	<tr>
		<th>异步响应类:</th>
		<td>${metaService.notifyClass}</td>
	</tr>					
	<tr>
		<th>创建时间:</th>
		<td>${metaService.createTime}</td>
	</tr>					
	<tr>
		<th>修改时间:</th>
		<td>${metaService.updateTime}</td>
	</tr>					
</table>
</div>
