<div style="padding: 5px;font-family:微软雅黑;">
<table class="tableForm" width="100%">
	<tr>
		<th>ID:</th>
		<td>${orderInfo.id}</td>
	</tr>					
	<tr>
		<th width="25%">访问key:</th>
		<td>${orderInfo.accessKey}</td>
	</tr>					
	<tr>
		<th>商户ID:</th>
		<td>${orderInfo.partnerId}</td>
	</tr>					
	<tr>
		<th>统一流水:</th>
		<td>${orderInfo.gid}</td>
	</tr>					
	<tr>
		<th>请求号:</th>
		<td>${orderInfo.requestNo}</td>
	</tr>					
	<tr>
		<th>服务名:</th>
		<td>${orderInfo.service}</td>
	</tr>					
	<tr>
		<th>版本号:</th>
		<td>${orderInfo.version}</td>
	</tr>					
	<tr>
		<th>签名类型:</th>
		<td>${orderInfo.signType}</td>
	</tr>					
	<tr>
		<th>协议:</th>
		<td>${orderInfo.protocol}</td>
	</tr>					
	<tr>
		<th>通知地址:</th>
		<td>${orderInfo.notifyUrl}</td>
	</tr>					
	<tr>
		<th>返回地址:</th>
		<td>${orderInfo.returnUrl}</td>
	</tr>					
	<tr>
		<th>扩展信息:</th>
		<td>${orderInfo.businessInfo}</td>
	</tr>					
	<tr>
		<th>会话信息:</th>
		<td>${orderInfo.context}</td>
	</tr>					
	<tr>
		<th>创建时间:</th>
		<td>${orderInfo.rawAddTime}</td>
	</tr>					
	<tr>
		<th>修改时间:</th>
		<td>${orderInfo.rawUpdateTime}</td>
	</tr>					
</table>
</div>
