<div class="card-body">
	<dl class="row">
		<dt class="col-sm-3">ID:</dt>
		<dd class="col-sm-9">${workOrder.id}</dd>
		<dt class="col-sm-3">单号:</dt>
		<dd class="col-sm-9">${workOrder.orderNo}</dd>
		<dt class="col-sm-3">业务线:</dt>
		<dd class="col-sm-9">${workOrder.busiLine.message()}</dd>
		<dt class="col-sm-3">产品线:</dt>
		<dd class="col-sm-9">${workOrder.productLine.message()}</dd>
		<dt class="col-sm-3">工单标题:</dt>
		<dd class="col-sm-9">${workOrder.title}</dd>
		<dt class="col-sm-3">工单类型:</dt>
		<dd class="col-sm-9">${workOrder.orderType.message()}</dd>
		<dt class="col-sm-3">要求完成时间:</dt>
		<dd class="col-sm-9">${workOrder.planTime?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">解决时间:</dt>
		<dd class="col-sm-9">${workOrder.fixedTime?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">工单优先级:</dt>
		<dd class="col-sm-9">${workOrder.orderPriority.message()}</dd>
		<dt class="col-sm-3">客户编码（冗余预留）:</dt>
		<dd class="col-sm-9">${workOrder.customerNo}</dd>
		<dt class="col-sm-3">客户名称:</dt>
		<dd class="col-sm-9">${workOrder.customerName}</dd>
		<dt class="col-sm-3">客户电话:</dt>
		<dd class="col-sm-9">${workOrder.customerPhone}</dd>
		<dt class="col-sm-3">客户邮箱:</dt>
		<dd class="col-sm-9">${workOrder.customerEmail}</dd>
		<dt class="col-sm-3">客户其他联系信息:</dt>
		<dd class="col-sm-9">${workOrder.customerInfo}</dd>
		<dt class="col-sm-3">受理人用户:</dt>
		<dd class="col-sm-9">${workOrder.acceptUser}</dd>
		<dt class="col-sm-3">受理人姓名:</dt>
		<dd class="col-sm-9">${workOrder.acceptName}</dd>
		<dt class="col-sm-3">处理人用户:</dt>
		<dd class="col-sm-9">${workOrder.handlerUser}</dd>
		<dt class="col-sm-3">处理人姓名:</dt>
		<dd class="col-sm-9">${workOrder.handlerName}</dd>
		<dt class="col-sm-3">历史处理人:</dt>
		<dd class="col-sm-9">${workOrder.handlers}</dd>
		<dt class="col-sm-3">完成时间:</dt>
		<dd class="col-sm-9">${workOrder.completeTime?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">工单状态:</dt>
		<dd class="col-sm-9">${workOrder.orderStatus.message()}</dd>
		<dt class="col-sm-3">创建时间:</dt>
		<dd class="col-sm-9">${workOrder.createTime?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">更新时间:</dt>
		<dd class="col-sm-9">${workOrder.updateTime?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">备注:</dt>
		<dd class="col-sm-9">${workOrder.comments}</dd>
	</dl>
</div>
