<div style="padding: 5px;font-family:微软雅黑;">
<table class="tableForm" width="100%">
	<tr>
		<th>id:</th>
		<td>${docItem.id}</td>
	</tr>					
	<tr>
		<th width="25%">parent_id:</th>
		<td>${docItem.parentId}</td>
	</tr>					
	<tr>
		<th>字段编号:</th>
		<td>${docItem.itemNo}</td>
	</tr>					
	<tr>
		<th>字段名称:</th>
		<td>${docItem.name}</td>
	</tr>					
	<tr>
		<th>字段标题:</th>
		<td>${docItem.title}</td>
	</tr>					
	<tr>
		<th>字段长度:</th>
		<td>${docItem.dataLength}</td>
	</tr>					
	<tr>
		<th>数据类型:</th>
		<td>${docItem.dataType}</td>
	</tr>					
	<tr>
		<th>字段描述:</th>
		<td>${docItem.descn}</td>
	</tr>					
	<tr>
		<th>字段示例:</th>
		<td>${docItem.demo}</td>
	</tr>					
	<tr>
		<th>可选状态:</th>
		<td>${docItem.status}</td>
	</tr>					
	<tr>
		<th>是否加密:</th>
		<td>${docItem.encryptstatus.message()}</td>
	</tr>					
	<tr>
		<th>备注:</th>
		<td>${docItem.comments}</td>
	</tr>					
	<tr>
		<th>创建时间:</th>
		<td>${docItem.createTime}</td>
	</tr>					
	<tr>
		<th>修改时间:</th>
		<td>${docItem.updateTime}</td>
	</tr>					
	<tr>
		<th>max:</th>
		<td>${docItem.max}</td>
	</tr>					
	<tr>
		<th>message_no:</th>
		<td>${docItem.messageNo}</td>
	</tr>					
	<tr>
		<th>min:</th>
		<td>${docItem.min}</td>
	</tr>					
	<tr>
		<th>parent_no:</th>
		<td>${docItem.parentNo}</td>
	</tr>					
	<tr>
		<th>signatrue:</th>
		<td>${docItem.signatrue}</td>
	</tr>					
	<tr>
		<th>sort_time:</th>
		<td>${docItem.sortTime}</td>
	</tr>					
</table>
</div>
