CREATE TABLE `acooly_coder_customer` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `username` varchar(32) NOT NULL COMMENT '{title:’用户名’,type:’account’}',
    `age` tinyint(4) DEFAULT NULL COMMENT '年龄',
    `birthday` date NOT NULL COMMENT '生日',
    `gender` varchar(16) NOT NULL COMMENT '{title:''性别’,alias: ‘gender’}',
    `animal` varchar(16) DEFAULT NULL COMMENT '{title:’生肖’, alias: ‘animal’}',
    `real_name` varchar(16) NOT NULL COMMENT '{title:’姓名’,type:’chinese’}',
    `idcard_type` varchar(18) NOT NULL COMMENT '{title:’证件类型’, type:’option’,options:{cert:’身份证‘,pass:’护照‘,other:’其他‘}}',
    `idcard_no` varchar(48) NOT NULL COMMENT '{title:’身份证号码’,type:’idcard’}',
    `bank_card_no` varchar(48) NOT NULL COMMENT '{title:’银行卡卡号’,type:’bankcard’}',
    `mobile_no` varchar(11) DEFAULT NULL COMMENT '{title:’手机号码’,type:’mobile’}',
    `mail` varchar(64) DEFAULT NULL COMMENT '{title:’邮件’,type:’email’}',
    `customer_type` varchar(16) DEFAULT NULL COMMENT '{title:’客户类型’, type:’option’,options:{normal:’普通‘,vip:’重要‘,sepc:’特别‘}}',
    `subject` varchar(128) DEFAULT NULL COMMENT '摘要',
    `content` text COMMENT '详情',
    `done_ratio` int(11) DEFAULT NULL COMMENT '{title:’完成度‘,type:’percent’}',
    `salary` int(11) DEFAULT NULL COMMENT '{title:’薪水’,type:’money’}',
    `registry_channel` varchar(16) DEFAULT NULL COMMENT '{title:’注册渠道’, alias: ‘channel’}',
    `push_adv` varchar(16) DEFAULT NULL COMMENT '{title:’推送广告’, alias:’whether’}',
    `num_status` tinyint(4) DEFAULT NULL COMMENT '数字类型{1:A,2:B,3:C类型}',
    `website` varchar(128) DEFAULT NULL COMMENT '{title:’网址’,type:’url’}',
    `photo_path` varchar(128) DEFAULT NULL COMMENT '{title:’照片’,type:‘file’}',
    `status` varchar(16) NOT NULL DEFAULT '1' COMMENT '{title:’状态’, alias:’simple’}',
    `create_time` datetime NOT NULL COMMENT '创建时间',
    `update_time` datetime NOT NULL COMMENT '更新时间',
    `comments` varchar(255) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COMMENT='acoolycoder测试';
