<div style="padding: 5px;font-family:微软雅黑;">
<table class="tableForm" width="100%">
	<tr>
		<th>ID:</th>
		<td>${customer.id}</td>
	</tr>					
	<tr>
		<th width="25%">用户名:</th>
		<td>${customer.username}</td>
	</tr>					
	<tr>
		<th>生日:</th>
		<td>${customer.birthday?string('yyyy-MM-dd HH:mm:ss')}</td>
	</tr>					
	<tr>
		<th>年龄:</th>
		<td>${customer.age}</td>
	</tr>					
	<tr>
		<th>性别:</th>
		<td>${customer.gender.message()}</td>
	</tr>					
	<tr>
		<th>生肖:</th>
		<td>${customer.animal.message()}</td>
	</tr>					
	<tr>
		<th>姓名:</th>
		<td>${customer.realName}</td>
	</tr>					
	<tr>
		<th>证件类型:</th>
		<td>${customer.idcardType.message()}</td>
	</tr>					
	<tr>
		<th>身份证号码:</th>
		<td>${customer.idcardNo}</td>
	</tr>					
	<tr>
		<th>银行卡卡号:</th>
		<td>${customer.bankCardNo}</td>
	</tr>					
	<tr>
		<th>手机号码:</th>
		<td>${customer.mobileNo}</td>
	</tr>					
	<tr>
		<th>邮件:</th>
		<td>${customer.mail}</td>
	</tr>					
	<tr>
		<th>客户类型:</th>
		<td>${customer.customerType.message()}</td>
	</tr>					
	<tr>
		<th>摘要:</th>
		<td>${customer.subject}</td>
	</tr>					
	<tr>
		<th>详情:</th>
		<td>${customer.content}</td>
	</tr>					
	<tr>
		<th>完成度:</th>
		<td>${customer.doneRatio}</td>
	</tr>					
	<tr>
		<th>付款率:</th>
		<td>${customer.payRate}</td>
	</tr>					
	<tr>
		<th>薪水:</th>
		<td>${customer.salary}</td>
	</tr>					
	<tr>
		<th>注册渠道:</th>
		<td>${customer.registryChannel.message()}</td>
	</tr>					
	<tr>
		<th>推送广告:</th>
		<td>${customer.pushAdv.message()}</td>
	</tr>					
	<tr>
		<th>数字类型:</th>
		<td>${allNumStatuss?api.get(customer.numStatus)}</td>
	</tr>					
	<tr>
		<th>网址:</th>
		<td>${customer.website}</td>
	</tr>					
	<tr>
		<th>照片:</th>
		<td>${customer.photoPath}</td>
	</tr>					
	<tr>
		<th>状态:</th>
		<td>${customer.status.message()}</td>
	</tr>					
	<tr>
		<th>创建时间:</th>
		<td>${customer.createTime}</td>
	</tr>					
	<tr>
		<th>更新时间:</th>
		<td>${customer.updateTime}</td>
	</tr>					
	<tr>
		<th>备注:</th>
		<td>${customer.comments}</td>
	</tr>					
</table>
</div>
